// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMm7wS5aNoDTqwy1RLMiOZqozkQzj_zbQ',
    appId: '1:463327277052:web:ee99b05987fb061cdccc79',
    messagingSenderId: '463327277052',
    projectId: 'take-home-quiz-f44c9',
    authDomain: 'take-home-quiz-f44c9.firebaseapp.com',
    storageBucket: 'take-home-quiz-f44c9.firebasestorage.app',
    measurementId: 'G-XXCHNY34WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOaAFsYExoQUEyfcf4L-AhM_NUg8_tke0',
    appId: '1:919335862380:android:159c71d9a29ff811c9d849',
    messagingSenderId: '919335862380',
    projectId: 'takehome-quiz-243e7',
    storageBucket: 'takehome-quiz-243e7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHKK0WXLctrjpVv4Bl5gxhxXJGeE96R_k',
    appId: '1:919335862380:web:5bc2c2df5430eecfc9d849',
    messagingSenderId: '919335862380',
    projectId: 'takehome-quiz-243e7',
    authDomain: 'takehome-quiz-243e7.firebaseapp.com',
    storageBucket: 'takehome-quiz-243e7.firebasestorage.app',
    measurementId: 'G-QSGR08MHR2',
  );

}